---
title: "Climate Change Vulnerability Assessments for Pacific Salmon & Steelhead in Canada"
subtitle: "Supplemental Information"
author: "Steph Peacock, Salmon Watersheds Program, Pacific Salmon Foundation"
date: "`r Sys.Date()`"
bibliography: references.json
csl: canadian-journal-of-fisheries-and-aquatic-sciences.csl 
link-citations: true
header-includes:
   - \usepackage{draftwatermark}
output: 
 html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    number_sections: true
  # word_document:
editor_options: 
  chunk_output_type: console
runtime: shiny
---

```{r setup, include=FALSE}

library(knitr)
opts_chunk$set(echo = TRUE)

```

<head>

<meta name="robots" content="noindex">

</head>

```{=html}
<style type="text/css">

.watermark {
  opacity: 0.2;
  position: fixed;
  top: 50%;
  left: 50%;
  font-size: 500%;
  color: #000000;
}

.blackbox {
 padding: 1em;
  background: black;
  color: white;
  border: 2px solid orange;
  border-radius: 10px;
}
.center {
  text-align: center;
}

</style>
```



# Background

This interactive document contains **Supplemental Information** that accompany the paper "Climate Change Vulnerability Assessments for Pacific Salmon & Steelhead in Canada". This work was led by Steph Peacock with the Pacific Salmon Foundation's [Salmon Watershed Program](https://www.salmonwatersheds.ca) in collaboration with members of PSF's Climate Science Advisory Committee and funded by the BC Salmon Restoration and Innovation Fund. 

The goal of this project is to quantify the relative **exposure** of different Conservation Units (CUs) to climate changes throughout their life cycles, with the aim to understand which CUs are likely to be most strongly affected and why. This information is key to informing proactive and forward-looking strategies for improving the resilience of salmon under climate change.  

# Results

::: {.blackbox data-latex=""}
::: {.center data-latex=""}
**This work is in the draft stage and all methods & results should be considered preliminary and subject to change.**
:::

Data update in progress...check back soon! (Feb 9, 2024)

:::

